### ISSUE TITLE
Nombre de Test

### ISSUE THREAD

**Issue by jmcrispino** [jCovidUnlam/Jzork#2]
https://github.com/jCovidUnlam/Jzork/blob/323368e2a23815b7d23d56ddaeb745e456f42c51/JZorkTest/jZorkTests/TestInventario.java#L47

El nombre de test debe ser lo mas representativo de lo que se esta probando. Aqui parece que testea que haya dos elementos. El test debería nombrarse, queExistenDosObjetosEnLugar

**Comment by noelisasha** [comment]
Issue corregido para la segunda entrega
