### ISSUE TITLE
Constantes

### ISSUE THREAD

**Issue by jmcrispino** [jCovidUnlam/Jzork#3]
https://github.com/jCovidUnlam/Jzork/blob/323368e2a23815b7d23d56ddaeb745e456f42c51/JZorkTest/jZorkTests/TestObstaculo.java#L18

Estas constantes que aparecen en los test, deberían ser parte del mapa u otro Objeto que represente un movimiento.

**Comment by noelisasha** [comment]
Issue corregido para la segunda entrega
