### ISSUE TITLE
Nombre métodos de los Test

### ISSUE THREAD

**Issue by jmcrispino** [jCovidUnlam/Jzork#4]
https://github.com/jCovidUnlam/Jzork/blob/323368e2a23815b7d23d56ddaeb745e456f42c51/JZorkTest/jZorkTests/TestPersonaje.java#L25

Tratar de no llamar test. Pueden optar por algo más representativo, ya lo comente antes.
Pueden llamarlo queNombreDePersonajeSeaCorrecto

**Comment by noelisasha** [comment]
Issue corregido para la segunda entrega
